server:
  port: 8082

spring:
  application:
    name: auth-service
  config:
    import: ${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: service, security, db
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: WmgtELUlBu49LGYg3Qfbup2EuZpSIU3L
    realm: eselpo
    serverUrl: ${KEYCLOAK_URL:http://localhost:8080/}