server:
  port: 8082

spring:
  application:
    name: auth-service
  config:
    import: ${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: service, security, db, admin-realm
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

spring-doc:
  swagger-ui:
    path: /api/v1/auth/swagger
  api-docs:
    path: /api/v1/auth/v3/api-docs
  default-produces-media-type: application/json