spring:
  application:
    name: entity
  config:
    import: http://host.docker.internal:8888/
  profiles:
    active: service
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/${MAIN_POSTGRES_DB}
    username: ${MAIN_POSTGRES_USER}
    password: ${MAIN_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect