server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/api/v1/test/**
            - Method=POST,GET,PUT,DELETE,PATCH
        - id: auth
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/v1/auth/**
            - Method=POST,GET,PUT,DELETE,PATCH
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: localhost
    non-secure-port: 8765
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka


logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"