#include:
#  - keycloak-compose.yml

services:
  config-server:
    image: maksim25y/config-server
    container_name: config-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8888:8888"a
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/application/default/main" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend
  registry:
    image: maksim25y/eureka-server
    container_name: eureka-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend

  auth-service:
    image: maksim25y/auth-service
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      registry:
        condition: service_healthy
    networks:
      - backend

  test-service:
    image: maksim25y/test-service
    container_name: test-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8083:8083"
    depends_on:
      registry:
        condition: service_healthy
    networks:
      - backend

  api-gateway:
    image: maksim25y/api-gateway
    container_name: api-gateway
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8765:8765"
    depends_on:
      registry:
        condition: service_healthy
      auth-service:
        condition: service_started
      test-service:
        condition: service_started
    networks:
      - backend

networks:
  backend: {}

