#include:
#  - keycloak-compose.yml

services:
  registry:
    build:
      context: ../eureka-server
      dockerfile: ../eureka-server/eureka.Dockerfile
    container_name: eureka_server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - my_network

  auth-service:
    build:
      context: ../auth-service
      dockerfile: ../auth-service/auth.Dockerfile
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      registry:
        condition: service_healthy
    networks:
      - my_network

  test-service:
    build:
      context: ../test-service
      dockerfile: ../test-service/test.Dockerfile
    container_name: test-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8083:8083"
    depends_on:
      registry:
        condition: service_healthy
    networks:
      - my_network

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: ../api-gateway/gateway.Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8765:8765"
    depends_on:
      registry:
        condition: service_healthy
      auth-service:
        condition: service_started
      test-service:
        condition: service_started
    networks:
      - my_network

networks:
  my_network: {}

