server:
  port: 8084

spring:
  application:
    name: user-service
  config:
    import: ${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: service, oauth2, db
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

spring-doc:
  swagger-ui:
    path: /api/v1/users/swagger
  api-docs:
    path: /api/v1/users/v3/api-docs
  default-produces-media-type: application/json

user:
  event:
    topic:
      name: user-events