server:
  port: 8084

spring:
  application:
    name: user-service
  config:
    import: ${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: service, oauth2, db
  mvc:
    hiddenmethod:
      filter:
        enabled: true