server:
  port: 8083

spring:
  application:
    name: test
  config:
    import: http://host.docker.internal:8888/
  profiles:
    active: service, oauth2
  mvc:
    hiddenmethod:
      filter:
        enabled: true