server:
  port: 0

spring:
  application:
    name: test
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springboot-microservice-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: "${spring.application.name}:${random.uuid}"

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"