name: Eureka server module workflow

on:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'eureka-server/**'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run build
        run: mvn package -Dskip.unit.tests=true

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run build
        run: mvn test